services:
  - type: web
    name: stock-advisor-india
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    plan: free
    region: oregon  # or "frankfurt", etc.
    healthCheckPath: /healthz
    envVars:
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
